site_name: Analysis Facility Docs
theme:
  name: material
  features:
    - instant
    - content.action.view

extra:
  deprecated:
    message:
      "⚠️ This documentation has been moved to the <a
      href='https://usatlas.github.io/af-docs/'>unified US ATLAS Analysis
      Facilities documentation</a>. Please update your bookmarks."

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.blocks.admonition

nav:
  - "Home": "index.md"
  - "Hardware": "hardware.md"
  - "Job submission": "job_submission.md"
  - "Coffea Casa": "coffeacasa.md"
  - "VSCode":
      - "Remote SSH": "VSCode_remote_ssh.md"
      - "Connecting to JupyterLab": "Connect_VSCode_to_JupyterLab.md"
  - "ServiceX": "servicex.md"
  - "ML platform": "ml_platform.md"
  - "Accessing data":
      - "Local DDM": "local-ddm.md"
      - "XCache": "xcache.md"
